version: "{build}"

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10

matrix:
  fast_finish: true

cache:
  - node_modules
  - flow-typed

platform: x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i
  - npm i --no-save pop-api
  - npm run flow-typed

build_script:
  - npm run build

test_script:
  - npm run lint
  - npm run flow -- check
  - npm run test

after_test:
  - npm run docs

artifacts:
  - path: build
  - path: coverage\lcov-report
    name: coverage
  - path: docs
